<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Calcurates\\Activator' => $baseDir . '/src/Activator.php',
    'Calcurates\\Assets' => $baseDir . '/src/Assets.php',
    'Calcurates\\HttpClient\\CalcuratesHttpClient' => $baseDir . '/src/HttpClient/CalcuratesHttpClient.php',
    'Calcurates\\HttpClient\\RequestsBodyBuilders\\RatesRequestBodyBuilder' => $baseDir . '/src/HttpClient/RequestsBodyBuilders/RatesRequestBodyBuilder.php',
    'Calcurates\\Logger' => $baseDir . '/src/Logger.php',
    'Calcurates\\Origins\\OriginUtils' => $baseDir . '/src/Origins/OriginUtils.php',
    'Calcurates\\Origins\\OriginsTaxonomy' => $baseDir . '/src/Origins/OriginsTaxonomy.php',
    'Calcurates\\RESTAPI\\WoocommerceOriginsRESTController' => $baseDir . '/src/RESTAPI/WoocommerceOriginsRESTController.php',
    'Calcurates\\RESTAPI\\WoocommerceSettingsRESTController' => $baseDir . '/src/RESTAPI/WoocommerceSettingsRESTController.php',
    'Calcurates\\Rates\\Extractors\\CarriersRatesExtractor' => $baseDir . '/src/Rates/Extractors/CarriersRatesExtractor.php',
    'Calcurates\\Rates\\Extractors\\FlatRatesRatesExtractor' => $baseDir . '/src/Rates/Extractors/FlatRatesRatesExtractor.php',
    'Calcurates\\Rates\\Extractors\\FreeShippingRatesExtractor' => $baseDir . '/src/Rates/Extractors/FreeShippingRatesExtractor.php',
    'Calcurates\\Rates\\Extractors\\InStorePickupsRatesExtractor' => $baseDir . '/src/Rates/Extractors/InStorePickupsRatesExtractor.php',
    'Calcurates\\Rates\\Extractors\\MergedShippingOptionsRatesExtractor' => $baseDir . '/src/Rates/Extractors/MergedShippingOptionsRatesExtractor.php',
    'Calcurates\\Rates\\Extractors\\RateShoppingRatesExtractor' => $baseDir . '/src/Rates/Extractors/RateShoppingRatesExtractor.php',
    'Calcurates\\Rates\\Extractors\\RatesExtractorAbstract' => $baseDir . '/src/Rates/Extractors/RatesExtractorAbstract.php',
    'Calcurates\\Rates\\Extractors\\RatesExtractorException' => $baseDir . '/src/Rates/Extractors/RatesExtractorException.php',
    'Calcurates\\Rates\\Extractors\\RatesExtractorFactory' => $baseDir . '/src/Rates/Extractors/RatesExtractorFactory.php',
    'Calcurates\\Rates\\Extractors\\TableRatesRatesExtractor' => $baseDir . '/src/Rates/Extractors/TableRatesRatesExtractor.php',
    'Calcurates\\Rates\\Rates' => $baseDir . '/src/Rates/Rates.php',
    'Calcurates\\WCBootstrap' => $baseDir . '/src/WCBootstrap.php',
    'Calcurates\\WCCalcurates' => $baseDir . '/src/WCCalcurates.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
