<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8e7447b7105363379ba015578067c4ee
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Calcurates\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Calcurates\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Calcurates\\Activator' => __DIR__ . '/../..' . '/src/Activator.php',
        'Calcurates\\Assets' => __DIR__ . '/../..' . '/src/Assets.php',
        'Calcurates\\HttpClient\\CalcuratesHttpClient' => __DIR__ . '/../..' . '/src/HttpClient/CalcuratesHttpClient.php',
        'Calcurates\\HttpClient\\RequestsBodyBuilders\\RatesRequestBodyBuilder' => __DIR__ . '/../..' . '/src/HttpClient/RequestsBodyBuilders/RatesRequestBodyBuilder.php',
        'Calcurates\\Logger' => __DIR__ . '/../..' . '/src/Logger.php',
        'Calcurates\\Origins\\OriginUtils' => __DIR__ . '/../..' . '/src/Origins/OriginUtils.php',
        'Calcurates\\Origins\\OriginsTaxonomy' => __DIR__ . '/../..' . '/src/Origins/OriginsTaxonomy.php',
        'Calcurates\\RESTAPI\\WoocommerceOriginsRESTController' => __DIR__ . '/../..' . '/src/RESTAPI/WoocommerceOriginsRESTController.php',
        'Calcurates\\RESTAPI\\WoocommerceSettingsRESTController' => __DIR__ . '/../..' . '/src/RESTAPI/WoocommerceSettingsRESTController.php',
        'Calcurates\\Rates\\Extractors\\CarriersRatesExtractor' => __DIR__ . '/../..' . '/src/Rates/Extractors/CarriersRatesExtractor.php',
        'Calcurates\\Rates\\Extractors\\FlatRatesRatesExtractor' => __DIR__ . '/../..' . '/src/Rates/Extractors/FlatRatesRatesExtractor.php',
        'Calcurates\\Rates\\Extractors\\FreeShippingRatesExtractor' => __DIR__ . '/../..' . '/src/Rates/Extractors/FreeShippingRatesExtractor.php',
        'Calcurates\\Rates\\Extractors\\InStorePickupsRatesExtractor' => __DIR__ . '/../..' . '/src/Rates/Extractors/InStorePickupsRatesExtractor.php',
        'Calcurates\\Rates\\Extractors\\MergedShippingOptionsRatesExtractor' => __DIR__ . '/../..' . '/src/Rates/Extractors/MergedShippingOptionsRatesExtractor.php',
        'Calcurates\\Rates\\Extractors\\RateShoppingRatesExtractor' => __DIR__ . '/../..' . '/src/Rates/Extractors/RateShoppingRatesExtractor.php',
        'Calcurates\\Rates\\Extractors\\RatesExtractorAbstract' => __DIR__ . '/../..' . '/src/Rates/Extractors/RatesExtractorAbstract.php',
        'Calcurates\\Rates\\Extractors\\RatesExtractorException' => __DIR__ . '/../..' . '/src/Rates/Extractors/RatesExtractorException.php',
        'Calcurates\\Rates\\Extractors\\RatesExtractorFactory' => __DIR__ . '/../..' . '/src/Rates/Extractors/RatesExtractorFactory.php',
        'Calcurates\\Rates\\Extractors\\TableRatesRatesExtractor' => __DIR__ . '/../..' . '/src/Rates/Extractors/TableRatesRatesExtractor.php',
        'Calcurates\\Rates\\Rates' => __DIR__ . '/../..' . '/src/Rates/Rates.php',
        'Calcurates\\WCBootstrap' => __DIR__ . '/../..' . '/src/WCBootstrap.php',
        'Calcurates\\WCCalcurates' => __DIR__ . '/../..' . '/src/WCCalcurates.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8e7447b7105363379ba015578067c4ee::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8e7447b7105363379ba015578067c4ee::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8e7447b7105363379ba015578067c4ee::$classMap;

        }, null, ClassLoader::class);
    }
}
